name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run Pnpm Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: jjs98/pnpm-install-action@v9
        with:
          no-frozen-lockfile: true

      - name: Build client
        run: pnpm build
        
  lint:
    name: Run linting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: jjs98/pnpm-install-action@v9
        with:
          no-frozen-lockfile: true
        
      - name: Run linting
        run: pnpm lint
        
  audit:
    name: Run audit
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: jjs98/pnpm-install-action@v9
        with:
          no-frozen-lockfile: true
        
      - name: Run audit
        run: pnpm audit

  karma:
    name: Run Unittests and SonarCloud
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: jjs98/pnpm-install-action@v9
        with:
          no-frozen-lockfile: true
        
      - name: Run Karma tests
        run: pnpm test

      - name: Copy coverage to correct path
        shell: pwsh
        run: |
          $file = Get-ChildItem -Path . -Recurse -Filter lcov.info | Select-Object -First 1
          Copy-Item -Path $file.FullName -Destination ./coverage/

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=jjs98
            -Dsonar.projectKey=jjs98_jjsware
            -Dsonar.verbose=false
            -Dsonar.exclusions=**/node_modules/**,src/assets/**
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

  playwright:
    name: Run playwright tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: jjs98/pnpm-install-action@v9
        with:
          no-frozen-lockfile: true
        
      - name: Install Playwright Browsers
        run: pnpm pw:install

      - name: Run Playwright tests
        run: pnpm pw

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 10

  docker:
    name: Build and push docker image
    needs: [build, lint, audit, karma, playwright]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        platform:
          - linux/arm64v8
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: jjs98/pnpm-install-action@v9
        with:
          no-frozen-lockfile: true

      - name: Build client
        run: pnpm build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: jjs98/jjsware-client

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: pnpm docker:build
        
      - name: Docker push
        run: pnpm docker:push
